image_source_dir: /Users/me/Bilder/Teams Hintergründe
msteams_upload_dir: /Users/me/Library/Containers/com.microsoft.teams2/Data/Library/Application Support/Microsoft/MSTeams/Backgrounds/Uploads
config_folder: /Users/mw/Library/Containers/com.microsoft.teams2/Data/Library/Application Support/Microsoft/MSTeams/Backgrounds/bg.db
overlay:
  enabled: true
  temp_dir: /tmp
  logo_file: /Users/me/Bilder/Icon-Overlays/Grey-Colour_RGB.png
  # If you have a light variant logo, you can specify it here
  #logo_file_light: /Users/me/Bilder/Icon-Overlays/White-Colour_RGB.png
  # The offset of the logo in pixel (negative values will start from the right/bottom)
  offset:
    x: 300
    y: 300
